GenresReplace = {
    '18-Year-Old': ['18', '18 year', 'eighteen and...'],
    'All Natural': ['natural'],
    'Amateur': ['amateur pre auditions', 'amatuer'],
    'Anal Fingering': ['ass fingering'],
    'Asian': ['asian amateur'],
    'Ass': ['booty', 'butt'],
    'Ass Eating': ['ass licking'],
    'Ass to Mouth': ['atm'],
    'Athletic Body': ['athlete', 'athletic'],
    'Ball Gag': ['ballgagged'],
    'Ball Licking': ['ball lick', 'ball sucking'],
    'Bareback': ['no condom'],
    'Barely Legal': ['barely-legal'],
    'BBW': ['big beautiful women'],
    'Behind the Scenes': ['behind the scene', 'bts'],
    'Big Butt': ['bib booty', 'big ass', 'big booty', 'big butts', 'fat ass', 'girl big ass'],
    'Big Dick': ['2 big cocks', 'big cock', 'big cocks', 'big dicks'],
    'Big Natural Tits': ['big naturals'],
    'Big Nipples': ['big areolas'],
    'Big Tits': ['big boobs', 'bit tits', 'girl big tits', 'large tits', 'busty'],
    'Big Toys': ['big toy'],
    'Bikini': ['bikin'],
    'Blonde': ['blond', 'blond hair', 'blonde hair', 'blondes'],
    'Blow Bang': ['blowbang'],
    'Blowjob': ['amateur blowjobs', 'bj', 'blow jobs', 'blowjob', 'blowjob (double)', 'blowjob (pov)', 'blowjob - double', 'blowjob - pov', 'blowjobs'],
    'Boots': ['boot'],
    'Boy-Boy-Boy-Girl': ['mmmf'],
    'Boy-Boy-Girl': ['bbg', 'mmf', 'threesome bbg'],
    'Boy-Boy-Girl-Girl': ['mmff'],
    'Boy-Boy-Girl-Girl-Girl': ['fffmm'],
    'Boy-Girl': ['boy girl', 'girl-boy', 'girl/boy'],
    'Boy-Girl-Girl': ['2 girl bj', 'bgg', 'ffm', 'girl-girl-boy', 'threesome bgg'],
    'Breast Bondage': ['best bound breasts'],
    'Brunette': ['brown hair', 'brunet', 'brunettes'],
    'Bukkake': ['bukakke'],
    'Butt Plug': ['anal plug', 'buttplug'],
    'Camel Toe': ['camel toe pussy'],
    'Caucasian': ['while', 'white', 'white girl', 'white girls', 'caucasian actress', 'white actress'],
    'CBT': ['death defying cbt'],
    'Chastity Play': ['chastity'],
    'Coeds': ['coed', 'college', 'university'],
    'Colored Hair': ['hair color', 'other hair color'],
    'Cop': ['police'],
    'Couple': ['couples'],
    'Cosplay': ['costume', 'uniform'],
    'Creampie': ['cream pie', 'creampie compilation'],
    'Cuckold': ['brutal cuckolding', 'cuckolding'],
    'Cum In Mouth': ['cum-in-mouth'],
    'Cumshot': ['cum shot', 'cum'],
    'Cum Swallowing': ['cum swallow', 'cum swallowers', 'swallow cum', 'swallowing cum'],
    'Cum Swap': ['cum swapping', 'cumswap'],
    'Curly Hair': ['curly'],
    'Curvy': ['curvy woman', 'thick', 'voluptuous'],
    'Deep Throat': ['deepthroat', 'deepthroating'],
    'Dildo': ['dildo play'],
    'Dirty Talk': ['dirty talking'],
    'Double Penetration (DP)': ['double penetration', 'double penetraton (dp)', 'dp'],
    'Ebony': ['african american', 'black', 'black girl', 'dark skin'],
    'Electro Play': ['electrical play', 'electrode punishments'],
    'European': ['euro', 'europe'],
    'Face Fucking': ['face fuck', 'facefucking', 'facefuck'],
    'Face Sitting': ['facesitting', 'queening'],
    'Facial': ['cumshot facial', 'facial (multiple)', 'facial (pov)', 'facial - pov', 'facials', 'open mouth facial'],
    'Fair Skin': ['pale', 'pale skin', 'whiteskin'],
    'Fake Tits': ['enhanced', 'enhanced tits', 'fake boobs', 'silicone tits'],
    'Feet': ['barefeet', 'foot'],
    'Fingering': ['finger fucking'],
    'First Anal': ['first time anal'],
    'First Appearance': ['debut', 'first porn shoot', 'first time porn', 'model debut'],
    'First Interracial': ['first time ir'],
    'Fishnets': ['fishnet', 'fishnet stockings'],
    'Fisting': ['fisting\'s finest'],
    'Foot Job': ['footjob', 'footjobs'],
    'Gangbang': ['gangbangs'],
    'Gaping': ['gape', 'gaped ass', 'gaping playlist'],
    'Girl-Girl': ['girl girl', 'girl on girl', 'girl-on-girl'],
    'Girl-Girl Pissing': ['girl girl pissing', 'lesbian pissing'],
    'Girlfriend Experience': ['gfe'],
    'Glamorous': ['glamour'],
    'Group Sex': ['group'],
    'Gym': ['gym selfie porn', 'in the gym'],
    'Hairy Pussy': ['bush', 'hairy', 'hairy bush'],
    'Hand Job': ['handjob', 'handjob (pov)', 'handjob - pov', 'handjobs'],
    'Hardcore': ['hardcore sex'],
    'Heterosexual': ['straight', 'straight porn'],
    'High Heels': ['heels'],
    'Holidays': ['holidayparty'],
    'Hood': ['hooded'],
    'Hotel Room': ['hotel'],
    'Housewife': ['housewives'],
    'Indoors': ['indoor'],
    'Interview': ['interviews'],
    'Interracial': ['ir'],
    'Jerk Off Instructions (JOI)': ['jerk off instruction', 'joi', 'joi games'],
    'Landing Strip': ['landing strip pussy'],
    'Latex': ['latex darlings'],
    'Latina': ['latinas'],
    'Lesbian': ['lesbians'],
    'Lezdom': ['lesbian domination'],
    'Lingerie': ['lenceria'],
    'Maid': ['maid fetish'],
    'Mask': ['masks'],
    'Massage': ['body massage'],
    'Masturbation': ['masturbacion'],
    'Medical Fetish': ['doctor', 'doctor/nurse', 'nurse', 'nurse play'],
    'Medium Tits': ['medium boobs'],
    'MILF': ['milfs'],
    'MILF & Mature': ['mature & milf'],
    'Mini Skirt': ['miniskirts'],
    'Model': ['modelo'],
    'Muscular': ['muscle'],
    'Natural Tits': ['natural boobs', 'real tits'],
    'Nerd': ['nerdy'],
    'Nude': ['completely naked', 'naked'],
    'Office Setting': ['office'],
    'Oil': ['babyoil', 'oiled'],
    'Older/Younger': ['older / younger'],
    'One-On-One': ['1 on 1'],
    'Oral Sex': ['oral'],
    'Orgasms': ['amazing orgasms', 'orgasm'],
    'Orgy': ['four or more'],
    'Outdoor Sex': ['outdoors'],
    'Outdoors': ['outdoor'],
    'Paddle': ['paddling'],
    'Panties': ['braguitas'],
    'Pantyhose & Stockings': ['black stockings', 'nude stockings', 'nylons stockings', 'pantyhose', 'pantyhose / stockings', 'pantyhose footjobs', 'stocking', 'stockings'],
    'Petite': ['skinny'],
    'Piercing': ['piercings'],
    'Pile Driver': ['pile driving'],
    'Piss Play': ['pee', 'pissing'],
    'Pool': ['poolparty'],
    'Pornstar': ['pornstars', 'porn star'],
    'Pornstar Experience': ['pse'],
    'POV': ['femdom pov', 'p.o.v.'],
    'Public Sex': ['public'],
    'Pussy Eating': ['cunilingus', 'pussy lick', 'pussy licking'],
    'Reality Porn': ['reality'],
    'Redhead': ['red head', 'red heads'],
    'Rim Job': ['rimjob', 'rimming'],
    'Schoolgirl Outfit': ['school girl', 'schoolgirl'],
    'Sci-Fi and Fantasy': ['sci fi'],
    'Sex': ['sexo'],
    'Shaven Pussy': ['bald pussy', 'shaved', 'shaved pussy'],
    'Shoe Fetish': ['shoeplay', 'sneaker fetish'],
    'Sissification': ['sissy training course'],
    'Skirt': ['skirts'],
    'Small Ass': ['small booty', 'small butt'],
    'Small Tits': ['small boobs'],
    'Solo': ['solo action', 'solo masturbation', 'solo sex'],
    'Squirting': ['squirt', 'top squirting videos'],
    'Step Daughter': ['stepdaughter'],
    'Step Mom': ['stepmom'],
    'Step Sister': ['ste sister', 'step sis', 'step siter', 'step-sister', 'stepsis', 'stepsister'],
    'Strap-On': ['pov strapon', 'strap on'],
    'Striptease': ['strip tease'],
    'Swallowing': ['amateur swallow', 'swallow'],
    'Tan': ['tanned skin'],
    'Tan Lines': ['tanlines'],
    'Tattoo': ['tattoo girl', 'tattooed', 'tattoos'],
    'Teacher Fetish': ['teacher'],
    'Tease and Denial': ['tease & denial'],
    'Teen': ['18+ teen', 'bad teens punished', 'teen porn', 'teen role', 'teens'],
    'Thong': ['thongs'],
    'Threesome': ['2 on 1', '2-on-1', '2on1', '3 way', '3some', 'threesomes'],
    'Titty Fuck': ['tit fuck', 'tit fucking', 'titty fucking', 'tittyfuck', 'tittyfuck (pov)', 'tittyfuck - pov', 'titfuck'],
    'Toys': ['sex toys', 'toy insertions'],
    'Transsexual': ['trans', 'transexual', 'ts'],
    'Tribbing': ['scissoring'],
    'Trimmed Pussy': ['trimmed', 'trimmed bush'],
    'Uncircumcised': ['uncut dicks'],
    'Uniform': ['uniforms'],
    'Valentine\'s Day': ['valentines day'],
    'Whipping': ['whip'],
    '69 (Position)': ['69', '69 position', 'sixty-nine'],
    'Cowgirl (Position)': ['cow girl', 'cowgirl', 'cowgirl (pov)'],
    'Doggystyle (Position)': ['doggy style', 'doggystyle', 'doggy'],
    'Missionary (Position)': ['missionary', 'missionary (pov)', 'missionary - pov'],
    'Reverse Cowgirl (Position)': ['cowgirl - pov', 'reverse cow girl', 'reverse cowgirl', 'reverse cowgirl (pov)'],
}

GenresSkip = [
    '18+ teens',
    '18+teens',
    '4k',
    '60p',
    'acworthy',
    'april',
    'april showers',
    'babe',
    'babes',
    'beaverday',
    'bonus',
    'daylight savings',
    'desert apocalypse',
    'destruction',
    'episode',
    'exclusive',
    'extra update',
    'faces of pain',
    'feel me',
    'get sprung',
    'gonzo',
    'grey',
    'hd videos',
    'heavymetal',
    'irreconcilable slut',
    'keiran',
    'little runaway',
    'mr. cummings',
    'photos',
    'public disgrace\'s best',
    'ryan mclane',
    'show less',
    'show more',
    'site member',
    'smart',
    'spring cleaning',
    'st patrick\'s day',
    'the pope',
    'tj cummings',
    'tony',
    'twistys hard',
    'tyler steele',
    'van styles',
    'workitout',
    'wow girls special',
    'yes, mistress',
]

GenresPartialSkip = [
    '1080p',
    '5k',
    '60fps',
    'aprilfools',
    'chibbles',
    'folsom',
    'hd',
]
