GenresReplace = {
    '18-Year-Old': ['eighteen and...', '18', '18 year'],
    'All Natural': ['natural'],
    'Amateur': ['amatuer', 'amateur pre auditions'],
    'Anal Fingering': ['ass fingering'],
    'Asian': ['asian amateur'],
    'Ass Eating': ['ass licking'],
    'Ass to Mouth': ['atm'],
    'Ass': ['butt', 'booty'],
    'Athletic body': ['athletic', 'athlete'],
    'Ball Gag': ['ballgagged'],
    'Ball Licking': ['ball licking', 'ball sucking', 'ball lick'],
    'Bareback': ['no condom'],
    'Barely Legal': ['barely-legal'],
    'BBW': ['big beautiful women'],
    'Behind The Scenes': ['behind the scene'],
    'Big Butt': ['big ass', 'big booty', 'bib booty', 'girl big ass', 'big butts', 'fat ass'],
    'big dick': ['big cock', 'big cocks', 'big dicks', '2 big cocks'],
    'Big Natural Tits': ['big naturals'],
    'Big Nipples': ['big areolas'],
    'Big Tits': ['big boobs', 'bit tits', 'girl big tits', 'large tits'],
    'Big Toys': ['big toy'],
    'Bikini': ['bikin'],
    'Blonde': ['blond', 'blonde hair', 'blondes', 'blond hair'],
    'Blow Bang': ['blowbang'],
    'Blow Job': ['blowjob', 'blowjob (pov)', 'blowjob (double)', 'bj', 'amateur blowjobs', 'blowjobs', 'blowjob - pov', 'blow jobs', 'blowjob - double'],
    'Boots': ['boot'],
    'Boy-Boy-Boy-Girl': ['mmmf'],
    'Boy-Boy-Girl': ['threesome bbg', 'mmf', 'bbg'],
    'Boy-Boy-Girl-Girl': ['mmff'],
    'Boy-Boy-Girl-Girl-Girl': ['fffmm'],
    'Boy-Girl': ['girl-boy', 'girl/boy', 'boy girl'],
    'Boy-Girl-Girl': ['bgg', 'threesome bgg', 'girl-girl-boy', 'ffm', '2 girl bj'],
    'Breast Bondage': ['best bound breasts'],
    'Brunette': ['brown hair', 'brunettes', 'brunet'],
    'Bukkake': ['bukakke'],
    'Butt Plug': ['buttplug', 'anal plug'],
    'Camel Toe': ['camel toe pussy'],
    'Caucasian': ['white', 'white girl', 'while'],
    'CBT': ['death defying cbt'],
    'Chastity Play': ['chastity'],
    'Coeds': ['college', 'university', 'coed'],
    'Colored Hair': ['hair color', 'other hair color'],
    'Cop': ['police'],
    'Couple': ['couples'],
    'Creampie': ['cream pie', 'creampie compilation'],
    'Cuckold': ['brutal cuckolding', 'cuckolding'],
    'Cum In Mouth': ['cum-in-mouth'],
    'Cum shot': ['cumshot'],
    'Cum Swallowing': ['cum swallow', 'swallow cum', 'swallowing cum', 'cum swallowers'],
    'Cum swap': ['cumswap', 'cum swapping'],
    'Curly hair': ['curly'],
    'Curvy': ['thick', 'voluptuous', 'curvy woman'],
    'Deep Throat': ['deepthroat', 'deepthroating'],
    'Dildo': ['dildo play'],
    'Dirty Talk': ['dirty talking'],
    'Double Penetration (DP)': ['dp', 'double penetration', 'double penetraton (dp)'],
    'Ebony': ['black', 'black girl', 'dark skin', 'african american'],
    'Electro Play': ['electrical play', 'electrode punishments'],
    'European': ['euro', 'europe'],
    'Face fucking': ['face fuck', 'facefucking'],
    'Face sitting': ['facesitting', 'queening'],
    'Facial': ['facial (multiple)', 'facial (pov)', 'cumshot facial', 'open mouth facial', 'facials', 'facial - pov'],
    'Fair Skin': ['pale', 'pale skin', 'whiteskin'],
    'Fake tits': ['enhanced', 'enhanced tits', 'silicone tits', 'fake boobs'],
    'Feet': ['foot', 'barefeet'],
    'Fingering': ['finger fucking'],
    'First anal': ['first time anal'],
    'First Appearance': ['first time porn', 'first porn shoot', 'debut', 'model debut'],
    'First Interracial': ['first time ir'],
    'Fishnets': ['fishnet', 'fishnet stockings'],
    'Fisting': ['fisting\'s finest'],
    'Foot Job': ['footjobs', 'footjob'],
    'Gangbang': ['gangbangs'],
    'Gaping': ['gape', 'gaping playlist', 'gaping', 'gaped ass'],
    'Girl-Girl Pissing': ['lesbian pissing', 'girl girl pissing'],
    'Girl-Girl': ['girl-on-girl', 'girl on girl', 'girl girl'],
    'Girlfriend Experience': ['gfe'],
    'Glamorous': ['glamour'],
    'Group sex': ['group'],
    'Gym': ['in the gym', 'gym selfie porn'],
    'Hairy pussy': ['hairy', 'hairy bush', 'bush'],
    'Hand job': ['handjob', 'handjob (pov)', 'handjobs', 'handjob - pov'],
    'Hardcore': ['hardcore sex'],
    'Heterosexual': ['straight', 'straight porn'],
    'High Heels': ['heels'],
    'Holidays': ['holidayparty'],
    'Hood': ['hooded'],
    'Hotel Room': ['hotel'],
    'Housewife': ['housewives'],
    'Indoors': ['indoor'],
    'Interview': ['interviews'],
    'Jerk Off Instructions (JOI)': ['jerk off instruction', 'joi', 'joi games'],
    'Landing Strip': ['landing strip pussy'],
    'Latex': ['latex darlings'],
    'Latina': ['latinas'],
    'Lesbian': ['lesbians'],
    'Lezdom': ['lesbian domination'],
    'Lingerie': ['lenceria'],
    'Maid': ['maid fetish'],
    'Mask': ['masks'],
    'Massage': ['body massage'],
    'Masturbation': ['masturbacion'],
    'Medical Fetish': ['nurse', 'doctor', 'nurse play', 'doctor/nurse'],
    'Medium Tits': ['medium boobs'],
    'MILF & Mature': ['mature & milf'],
    'MILF': ['milfs'],
    'Mini Skirt': ['miniskirts'],
    'Model': ['modelo'],
    'Muscular': ['muscle'],
    'Natural Tits': ['natural boobs', 'real tits'],
    'Nerd': ['nerdy'],
    'Nude': ['completely naked', 'naked'],
    'Office Setting': ['office'],
    'Oil': ['oiled', 'babyoil'],
    'Older/Younger': ['older / younger'],
    'One-On-One': ['1 on 1'],
    'Oral Sex': ['oral'],
    'Orgasms': ['orgasm', 'amazing orgasms'],
    'Orgy': ['four or more'],
    'Outdoor Sex': ['outdoors'],
    'Outdoors': ['outdoor'],
    'Paddle': ['paddling'],
    'Panties': ['braguitas'],
    'Pantyhose & Stockings': ['nude stockings', 'stockings', 'nylons stockings', 'pantyhose', 'pantyhose footjobs', 'black stockings', 'pantyhose / stockings', 'stocking'],
    'Piercing': ['piercings'],
    'Pile Driver': ['pile driving'],
    'Piss Play': ['pee', 'pissing'],
    'Pool': ['poolparty'],
    'Pornstar Experience': ['pse'],
    'Pornstar': ['pornstars'],
    'POV': ['p.o.v.', 'femdom pov'],
    'Pussy Eating': ['pussy lick', 'pussy licking', 'cunilingus'],
    'Reality Porn': ['reality'],
    'Redhead': ['red head', 'red heads'],
    'Rim Job': ['rimming', 'rimjob'],
    'Schoolgirl Outfit': ['school girl', 'schoolgirl'],
    'Sci-Fi and Fantasy': ['sci fi'],
    'Sex': ['sexo'],
    'Shaven pussy': ['shaved pussy', 'bald pussy', 'shaved'],
    'Shoe Fetish': ['sneaker fetish', 'shoeplay'],
    'Sissification': ['sissy training course'],
    'Skirt': ['skirts'],
    'Small Ass': ['small booty', 'small butt'],
    'Small Tits': ['small boobs'],
    'Solo': ['solo masturbation', 'solo sex', 'solo action'],
    'Squirting': ['squirt', 'top squirting videos'],
    'Step daughter': ['stepdaughter'],
    'Step mom': ['stepmom'],
    'Step sister': ['stepsister', 'stepsis', 'step sis', 'ste sister', 'step siter', 'step-sister'],
    'Strap-On': ['strap on', 'pov strapon'],
    'Striptease': ['strip tease'],
    'Swallowing': ['swallow', 'amateur swallow'],
    'Tan Lines': ['tanlines'],
    'Tan': ['tanned skin'],
    'Tattoo': ['tattoos', 'tattoo girl', 'tattooed'],
    'Teacher Fetish': ['teacher'],
    'Tease And Denial': ['tease & denial'],
    'Teen': ['teens', 'teen role', 'bad teens punished', 'teen porn', '18+ teen'],
    'Thong': ['thongs'],
    'Threesome': ['3some', '3 way', '2-on-1', '2on1', '2 on 1', 'threesomes'],
    'Titty fuck': ['tittyfuck (pov)', 'tittyfuck', 'tit fuck', 'titty fucking', 'tittyfuck - pov', 'tit fucking'],
    'Toys': ['sex toys', 'toy insertions'],
    'Transsexual': ['ts', 'transexual', 'trans'],
    'Tribbing': ['scissoring'],
    'Trimmed pussy': ['trimmed', 'trimmed bush'],
    'Uncircumcised': ['uncut dicks'],
    'Uniform': ['uniforms'],
    'Valentine\'s Day': ['valentines day'],
    'Whipping': ['whip'],
    '69 (Position)': ['sixty-nine', '69', '69 position'],
    'Cowgirl (Position)': ['cow girl', 'cowgirl', 'cowgirl (pov)'],
    'Doggystyle (Position)': ['doggystyle', 'doggy style'],
    'Missionary (Position)': ['missionary', 'missionary (pov)', 'missionary - pov'],
    'Reverse cowgirl (Position)': ['reverse cow girl', 'reverse cowgirl', 'reverse cowgirl (pov)', 'cowgirl - pov'],
}

GenresSkip = [
    '18+ teens',
    '18+teens',
    '4k',
    '60p',
    'acworthy',
    'april showers',
    'april',
    'babe',
    'babes',
    'beaverday',
    'bonus',
    'daylight savings',
    'desert apocalypse',
    'destruction',
    'episode',
    'exclusive',
    'extra update',
    'faces of pain',
    'feel me',
    'get sprung',
    'gonzo',
    'grey',
    'hd videos',
    'heavymetal',
    'irreconcilable slut',
    'keiran',
    'little runaway',
    'mr. cummings',
    'photos',
    'public disgrace\'s best',
    'ryan mclane',
    'show less',
    'show more',
    'site member',
    'smart',
    'spring cleaning',
    'st patrick\'s day',
    'the pope',
    'tj cummings',
    'tony',
    'twistys hard',
    'tyler steele',
    'van styles',
    'workitout',
    'wow girls special',
    'yes, mistress',
]

GenresPartialSkip = [
    '5k',
    '60fps',
    'hd',
    '1080p',
    'aprilfools',
    'chibbles',
    'folsom',
]
