ActorsReplace = {
    'Abbey Rain': ['Abby Rains'],
    'Abby Lee Brazil': ['Abby Lee'],
    'Abella Danger': ['Bella Danger'],
    'Addie Juniper': ['Ms Addie Juniper'],
    'Adriana Chechik': ['Adrianna Chechik', 'Adriana Chechick'],
    'Alex D.': ['Alex D'],
    'Alura Jenson': ['Alura Tnt Jenson', 'Alura \'Tnt\' Jenson'],
    'Amia Miley': ['Amia Moretti'],
    'Amy Ried': ['Amy Reid'],
    'Ana Foxxx': ['Ana Fox', 'Ana Foxx'],
    'Anastasia Morna': ['Anna Morna'],
    'Andreina Deluxe': ['Andreina De Lux', 'Andreina De Luxe', 'Andreina Dlux'],
    'Angel Piaff': ['Angela Piaf', 'Angel Piaf'],
    'Angie Moon': ['Angelina Mori'],
    'Ani Blackfox': ['Ani Black Fox', 'Ani Black'],
    'Anita Bellini Berlusconi': ['Anita Bellini'],
    'Anna De Ville': ['Anna Deville', 'Anna DeVille'],
    'Annika Albrite': ['Anikka Albrite'],
    'April O\'Neil': ['April ONeil', 'April Oneil', 'April O\'neil'],
    'Ashlee Graham': ['Ashley Graham'],
    'Ashly Anderson': ['Ashley Anderson'],
    'Black Angelika': ['Angelika Black', 'Black Angelica'],
    'Bridgette B': ['Bridgette B.'],
    'Britney Beth': ['Bibi Jones', 'Bibi Jones™'],
    'Bunny Colby': ['Nadya Nabakova', 'Nadya Nabokova'],
    'Capri Cavanni': ['Capri Cavalli'],
    'Carry Cherry': ['Carrie Cherry', 'Carry Cherri', 'Corry Cherry', 'Kerry Cherry', 'Dormiona'],
    'CeCe Capella': ['Ce Ce Capella'],
    'Charlie Red': ['Charli Red'],
    'Chris Strokes': ['Criss Strokes'],
    'Clea Gaultier': ['CléA Gaultier'],
    'Connie Carter': ['Josephine', 'Conny', 'Conny Carter', 'Connie'],
    'Cyrstal Rae': ['Crystal Rae'],
    'Eden Sinclair': ['Eden Sin'],
    'Elsa Jean': ['Elsa Dream'],
    'Emma Fantasy': ['Emma Fantazy'],
    'Emma Hix': ['Crissy Kay', 'Emma Hicks', 'Emma Hixx'],
    'Eva Elfie': ['Tiny Teen', 'Tieny Mieny', 'Lady Jay', 'Tiny Teen / Eva Elfie'],
    'Eve Laurence': ['Eve Lawrence'],
    'Foxy Di': ['Foxi Di'],
    'Francesca DiCaprio': ['Francesca Di Caprio', 'Francesca Dicaprio'],
    'Gina Gerson': ['Doris Ivy'],
    'Goldie Glock': ['Goldie'],
    'Gulliana Alexis': ['Guiliana Alexis'],
    'Haley Reed': ['Hailey Reed'],
    'Isabel Stern': ['Isabel Sterov', 'Isabelle Stern'],
    'Jaye Summers': ['Charlotte Lee'],
    'Jenna Ross': ['Jenna J Ross', 'Jenna J. Ross'],
    'Jenny Fer': ['Jenny Ferri'],
    'Jessi Gold': ['Jassie Gold', 'Jaggie Gold'],
    'Jessica Foxx': ['Jessica Blue', 'Jessica Cute'],
    'Jojo Kiss': ['Jo Jo Kiss'],
    'Josephine Jackson': ['Josephina Jackson'],
    'Kagney Linn Karter': ['Kagney Lynn Karter'],
    'Kari Sweet': ['Kari Sweets'],
    'Katerina Hartlova': ['Katarina'],
    'Kendra Lust': ['Kendra May Lust'],
    'Khloe Kapri': ['Khloe Capri', 'Chloe Capri'],
    'Kristall Rush': ['Aurelly Rebel', 'Crystal Rush'],
    'Krystal Boyd': ['Anjelica', 'Ebbi', 'Abby H', 'Katherine A'],
    'Lilly Ford': ['Lilly Lit'],
    'Lily Labeau': ['Lilly LaBeau', 'Lilly Labuea', 'Lily La Beau', 'Lily Lebeau', 'Lily Luvs'],
    'Linda Brugal': ['Milana Witch'],
    'Lola Taylor': ['Lolita Taylor'],
    'Lora Craft': ['Lara Craft'],
    'Maddy O\'Reilly': ['Maddy OReilly', 'Maddy Oreilly', 'Maddy O\'reilly'],
    'Melena Maria Rya': ['Maria Rya', 'Melena Maria'],
    'Miss Jade Indica': ['Jade Indica'],
    'Moe Johnson': ['Moe The Monster Johnson'],
    'Nancy Ace': ['Nancy A.', 'Nancy A'],
    'Nathaly Cherie': ['Nathaly', 'Nathalie Cherie', 'Natalie Cherie'],
    'Nika Noire': ['Nika Noir'],
    'Noemilk': ['Noe Milk', 'Noemiek'],
    'Ornella Morgan': ['Ornella Morgen'],
    'Paula Shy': ['Christy Charming'],
    'Pinky June': ['Grace Hartley'],
    'Polina Maxim': ['Polina Maxima', 'Polina Max', 'Venera Maxima'],
    'Polly Pons': ['Polly Pon'],
    'Pristine Edge': ['Jane Doux'],
    'Pussy Kat': ['Pussykat'],
    'Rebel Lynn': ['Rebel Lynn (Contract Star)'],
    'Remy Lacroix': ['Remy La Croix'],
    'Riley Jensen': ['Riley Jenson', 'Riley Anne', 'Rilee Jensen'],
    'Riley Star': ['Riley Starr'],
    'Rosaline Rosa': ['Rosaline Rose'],
    'Sara Luvv': ['Sara Luv'],
    'Scarlet Domingo': ['Scarlet Rebel', 'Scarlett Rebel', 'Scarlett Domingo'],
    'Selvaggia Babe': ['Selvaggia'],
    'Shalina Divine': ['Shalina Devine'],
    'Shelley Bliss': ['Mia Ferrari'],
    'Skylar Vox': ['Dylann Vox', 'Dylan Vox'],
    'Sofi Smile': ['Sonia Smile', 'Sony Smile', 'Sofi Smail'],
    'Sofy Soul': ['Sofy Torn'],
    'Sonia Sweet': ['Soniy Sweet', 'Sonya Sweet'],
    'Stefanie Moon': ['Stephanie Moon', 'Steffy Moon'],
    'Stella Banxxx': ['Stella Bankxxx', 'Stella Ferrari'],
    'Stella Flex': ['Marselina Fiore', 'Marseling Fiote', 'Stella Shine'],
    'Stephanie Renee': ['Sedona', 'Stefanie Renee'],
    'Steven St. Croix': ['Steven St.Croix'],
    'Sybil A': ['Sybil Kailena', 'Sybil'],
    'Taissia Shanti': ['Taissia', 'Taisia', 'Taisia Shanti', 'Taissia Shanty', 'Taisha'],
    'Timea Bella': ['Lucianna Karel'],
    'Veronica Valentine': ['Veronica Vega'],
    'Viola Bailey': ['Viola Bailey’S'],
    'Yu Shinoda': ['Shinoda Yuu'],
    'Zoe Bloom': ['Zoey Bloom'],
}

ActorsReplaceStudios = {
    0: {
        'Henessy': ['Henna Ssy'],
        'Katarina Muti': ['Ariel Temple'],
        'Krystal Boyd': ['Abbie'],
        'Mishelle Klein': ['Molly A'],
        'Stefanie Moon': ['Stefanie'],
    },
    1: {
        'Aika May': ['Aiko May'],
        'Ariel Piper Fawn': ['Ariel'],
        'Katya Clover': ['Clover'],
        'Krystal Boyd': ['Angelica'],
    },
    2: {
        'Abella Anderson': ['Amy'],
        'Noemie Bilas': ['Noemi Bilas'],
    },
    3: {
        'Katy Rose': ['Katy E'],
        'Scarlet Domingo': ['Scarlet'],
    },
    4: {
        'Apolonia Lapiedra': ['Apolonia'],
        'Scarlet Domingo': ['Scarlett'],
    },
    5: {
        'Vika Lita': ['Vikalita'],
        'Vina Sky': ['Vina Skyy'],
    },
    6: {
        'Scarlet Domingo': ['Scarlett'],
    },
    7: {
        'Abigaile Johnson': ['Abigaile'],
        'Aletta Ocean': ['Aletta'],
        'Alexis Adams': ['Alexis'],
        'Alina Li': ['Alina'],
        'Allie Haze': ['Allie H'],
        'Allie Rae': ['Allie'],
        'Ashlyn Rae': ['Ashlyn'],
        'August Ames': ['August'],
        'Belle Knox': ['Belle'],
        'Bibi Jones': ['Brittany', 'Britney B'],
        'Brooklyn Chase': ['Brooklyn'],
        'Casana Lei': ['Casana'],
        'Casi James': ['Casi'],
        'Dillion Harper': ['Dillion'],
        'Dillion Harper': ['Dillon'],
        'Ella Milano': ['Ella M'],
        'Elsa Jean': ['Elsa'],
        'Emily Grey': ['Emily'],
        'Erin Stone': ['Erin'],
        'Evilyn Fierce': ['Evilyn'],
        'Haley Cummings': ['Haley'],
        'Hayden Winters': ['Hayden'],
        'Holly Michaels': ['Holly'],
        'Hope Howell': ['Hope'],
        'Isis Taylor': ['Isis'],
        'Janice Griffith': ['Janice'],
        'Jaslene Jade': ['Jaslene'],
        'Jayden Taylors': ['Jayden'],
        'Jenna Rose': ['Jenna'],
        'Jessica Robbins': ['Jessica'],
        'Jynx Maze': ['Jynx'],
        'Karina White': ['Karina'],
        'Kennedy Leigh': ['Kennedy'],
        'Kodi Gamble': ['Kodi'],
        'Lacy Channing': ['Lacy'],
        'Lexi Belle': ['Lexi'],
        'Lexi Bloom': ['Lexi B'],
        'Lexi Diamond': ['Lexi D'],
        'Lily Carter': ['Lily C'],
        'Lily Carter': ['Lily'],
        'Lily Love': ['Lily'],
        'Lizz Taylor': ['Lizz'],
        'Lola Foxx': ['Lola'],
        'Lucy Doll': ['Lucy'],
        'Madison Ivy': ['Madison'],
        'Mary Jane Johnson': ['Maryjane'],
        'Mia Malkova': ['Mia'],
        'Molly Bennett': ['Molly'],
        'Naomi West': ['Naomi'],
        'Nicole Ray': ['Nicole'],
        'Presley Carter': ['Presley'],
        'Pristine Edge': ['Pristine'],
        'Rebecca Linares': ['Rebecca'],
        'Remy LaCroix': ['Remy'],
        'Riley Reid': ['Riley'],
        'Scarlet Red': ['Scarlet'],
        'Staci Silverstone': ['Staci'],
        'Stacie Jaxx': ['Stacie'],
        'Stephanie Cane': ['Stephanie C'],
        'Teal Conrad': ['Tealey'],
        'Tessa Taylor': ['Tessa'],
        'Tori Black': ['Tori'],
        'Vanessa Cage': ['Vanessa'],
        'Victoria Rae Black': ['Victoria R'],
        'Victoria Rae Black': ['Victoria'],
        'Whitney Westgate': ['Whitney'],
        'Zoey Kush': ['Zoey'],
    },
    8: {
        'Scarlet Domingo': ['Scarlett'],
    },
    9: {
        'Foxy Di': ['Foxy D'],
        'Krystal Boyd': ['Abby'],
        'Sophia Traxler': ['Olivia'],
    },
    10: {
        'Abigaile Johnson': ['Abigail'],
        'Adele Sunshine': ['Sunny G.'],
        'Aleska Diamond': ['Aleska D.'],
        'Alessandra Jane': ['Alessandra J.'],
        'Alexa Tomas': ['Alexa'],
        'Alexis Brill': ['Alexis B.'],
        'Alexis Crystal': ['Alexis'],
        'Alexis Texas': ['Alexis T.'],
        'Alexis Venton': ['Alexis V.'],
        'Allie Jordan': ['Allie J.'],
        'Alyssa Branch': ['Alysa'],
        'Amirah Adara': ['Amirah A.'],
        'Andie Darling': ['Andie'],
        'Angel Blade': ['Angel B.'],
        'Anita Bellini Berlusconi': ['Anita B.'],
        'Apolonia Lapiedra': ['Apolonia'],
        'Ariel Piper Fawn': ['Ariel'],
        'Aubrey James': ['Aubrey J.'],
        'Avril Hall': ['Avril H.'],
        'Bailey Ryder': ['Bailey R.'],
        'Billie Star': ['Billie'],
        'Blanche Bradburry': ['Blanche B.'],
        'Brittney Banxxx': ['Brittany'],
        'Candice Luca': ['Candice'],
        'Candy Blond': ['Candy B.'],
        'Cara Mell': ['Rena'],
        'Carmen McCarthy': ['Carmen C.'],
        'Carolina Abril': ['Carolina'],
        'Cayenne Klein': ['Anna P.'],
        'Cayla Lyons': ['Cayla L.'],
        'Celeste Star': ['Celeste'],
        'Chastity Lynn': ['Chastity L.'],
        'Cherry Kiss': ['Cherry K.'],
        'Christen Courtney': ['Christen'],
        'Cindy Carson': ['Cindy L.'],
        'Cindy Dollar': ['Cindy D.'],
        'Clea Gaultier': ['Clea G'],
        'Coco de Mal': ['Coco'],
        'Connie Carter': ['Josephine'],
        'Dani Daniels': ['Dani D.'],
        'Defrancesca Gallardo': ['Defrancesca'],
        'Denisa Heaven': ['Denisa'],
        'Dido Angel': ['Lara'],
        'Elaina Raye': ['Eliana R.'],
        'Ella Milano': ['Ella M.'],
        'Emma Brown': ['Jana Q.'],
        'Erika Kortni': ['Erika K.'],
        'Eufrat Mai': ['Eufrat'],
        'Eveline Dellai': ['Eveline D.'],
        'Evi Fox': ['Evi F.'],
        'Evilyn Fierce': ['Evilyn F.'],
        'Faye Reagan': ['Faye R.'],
        'Ferrera Gomez': ['Ferrera'],
        'Foxy Di': ['Medina U.'],
        'Frida Sante': ['Frida S.'],
        'Gina Devine': ['Gina V.'],
        'Gina Gerson': ['Gina G.'],
        'Ginebra Bellucci': ['Ginebra B.'],
        'Ginger Fox': ['Ginger'],
        'Giselle Leon': ['Giselle L.'],
        'Hayden Winters': ['Hayden W.'],
        'Heather Starlet': ['Heather S.'],
        'Holly Anderson': ['Holly'],
        'Holly Michaels': ['Holly M.'],
        'Iwia': ['Ivy'],
        'Izzy Delphine': ['Delphine'],
        'Jana Jordan': ['Jana J.'],
        'Jayden Cole': ['Jayden C.'],
        'Jennifer White': ['Jennifer W.'],
        'Jessica Bee': ['Jessica B.'],
        'Jessie Jazz': ['Jessie'],
        'Julia Roca': ['Julia R.'],
        'Kaci Starr': ['Kaci S.'],
        'Kari Sweet': ['Kari'],
        'Karlie Montana': ['Karlie'],
        'Karol Lilien': ['Karol T.'],
        'Katie Jordin': ['Katie J.'],
        'Kattie Gold': ['Katie G.'],
        'Katy Rose': ['Katy R.'],
        'Katya Clover': ['Clover'],
        'Kelly White': ['Kelly W'],
        'Kiara Diane': ['Kiara D.'],
        'Kiara Lord': ['Kiara L.'],
        'Kira Thorn': ['Kira T.'],
        'Kitty Jane': ['Kitty J.'],
        'Lady Dee': ['Dee'],
        'Lena Nicole': ['Lena N.'],
        'Leony April': ['Jessica'],
        'Lexi Dona': ['Lexi D.'],
        'Lexi Swallow': ['Lexi S.'],
        'Lilu Moon': ['Lilu'],
        'Lily Carter': ['Lily B.'],
        'Lily Labeau': ['Lily L.'],
        'Little Caprice': ['Caprice'],
        'Lovenia Lux': ['Bailey D.'],
        'Lucy Heart': ['Lucy H.'],
        'Lucy Li': ['Lucy L.'],
        'Luna Corazon': ['Luna C.'],
        'Marie McCray': ['Maria C.'],
        'Marry Queen': ['Miela'],
        'Merry Pie': ['Patricya L.'],
        'Mia Manarote': ['Mia D.'],
        'Michaela Isizzu': ['Mila K.'],
        'Milana Blanc': ['Milana R.'],
        'Milena Devi': ['Milena D.'],
        'Mira Sunset': ['Alice B.'],
        'Misty Stone': ['Misty S.'],
        'Mona Lee': ['Mona L.'],
        'Monika Benz': ['Stacey'],
        'Nancy Ace': ['Jane F.'],
        'Natalie Nice': ['Natalie N.'],
        'Nataly Gold': ['Nataly G.'],
        'Nathaly Cherie': ['Natalli'],
        'Niki Sweet': ['Niky S.'],
        'Nikki Daniels': ['Nikki'],
        'Paula Shy': ['Paula S.'],
        'Paulina Soul': ['Paulina S'],
        'Pinky June': ['Anneli'],
        'Piper Perri': ['Piper P.'],
        'Presley Hart': ['Presley H.'],
        'Pristine Edge': ['Pristine E.'],
        'Reena Sky': ['Reena'],
        'Renee Perez': ['Renee P.'],
        'Ria Rodrigez': ['Ria R.'],
        'Rihanna Samuel': ['Rihanna'],
        'Riley Jensen': ['Riley'],
        'Rina Ellis': ['Rina'],
        'Rose Delight': ['Belinda'],
        'Sage Evans': ['Sage E.'],
        'Sally Charles': ['Sally C.'],
        'Sandy Ambrosia': ['Sandy A.'],
        'Sara Jaymes': ['Sara'],
        'Sara Luvv': ['Sara L.'],
        'Scarlet Banks': ['Scarlet B.'],
        'Shyla Jennings': ['Shyla G.'],
        'Shyla Jennings': ['Shyla'],
        'Silvie Deluxe': ['Simona'],
        'Sophia Jade': ['Sophia J.'],
        'Stella Cox': ['Stella C'],
        'Suzie Carina': ['Suzie'],
        'Sybil A': ['Davina E.'],
        'Tarra White': ['Tarra W.'],
        'Tasha Reign': ['Tasha R.'],
        'Taylor Vixen': ['Taylor V.'],
        'Teagan Summers': ['Tegan S.'],
        'Tess Lyndon': ['Tess L.'],
        'Tiffany Fox': ['Tiffany F.'],
        'Tiffany Thompson': ['Tiffany T.'],
        'Tina Blade': ['Tina'],
        'Tina Hot': ['Tina H.'],
        'Tracy Gold': ['Tracy A.'],
        'Tracy Lindsay': ['Tracy'],
        'Tracy Smile': ['Tracy S.'],
        'Tyra Moon': ['Athina'],
        'Uma Zex': ['Uma Z.'],
        'Valentina Nappi': ['Valentina N.'],
        'Vanda Lust': ['Vanda'],
        'Victoria Blaze': ['Victoria B.'],
        'Victoria Puppy': ['Victoria P.'],
        'Victoria Rae Black': ['Victoria R.'],
        'Victoria Sweet': ['Viktoria S.'],
        'Vinna Reed': ['Vinna R.'],
        'Viola Bailey': ['Vanea H.'],
        'Whitney Conroy': ['Whitney C.'],
        'Zazie Sky': ['Zazie S.'],
        'Zena Little': ['Lilly K.'],
        'Zoe Voss': ['Zoe V.'],
    },
    11: {
        'Jesse Jane': ['Jesse'],
    },
    12: {
        'Alana Evans': ['Alana'],
        'Anna Ashton': ['Sandy'],
        'Avy Scott': ['Avi Scott'],
        'Boo Delicious': ['Boo'],
        'Courtney Devine': ['Courtney'],
        'Deviant Kade': ['Kade'],
        'Diamond Foxxx': ['Diamond'],
        'Elyse Stone': ['Elyse'],
        'Emilie Davinci': ['Emily'],
        'Emily Marilyn': ['Molly Matthews'],
        'Harmony Rose': ['Harmony'],
        'Heather Starlet': ['Heather Starlett'],
        'Jassie James': ['Jassie'],
        'Julie Knight': ['Julie Night'],
        'Kristine Andrews': ['Kristine'],
        'Leah Parker': ['Leah'],
        'Liz Tyler': ['Cowgirl'],
        'Lola Milano': ['Alexa Jaymes'],
        'Melanie Jagger': ['Melanie'],
        'Meriesa Arroyo': ['Meriesa'],
        'Michelle Avanti': ['Michele Avanti'],
        'Nadine Sage': ['Naidyne'],
        'Natalia Wood': ['Danielle'],
        'Phoenix Ray': ['Phoenix'],
        'Phyllisha Anne': ['Phyllisha'],
        'Porsha Blaze': ['Porsha'],
        'Ramona Luv': ['Ramona'],
        'Sabrine Maui': ['Sabrine'],
        'Sara Jaymes': ['Sarah Jaymes'],
        'Sasha Sin': ['Sascha Sin'],
        'Teagan Summers': ['Tegan Summer'],
        'Wanda Curtis': ['Wanda'],
    },
    13: {
        'Heather Harmon': ['Imheatherharmon'],
        'Shaiden Rogue': ['Shaiden'],
        'Spencer Bradley': ['Spencer_Bradley'],
    },
    14: {
        'Scarlet Domingo': ['Scarlett'],
    },
    15: {
        'Abby Cross': ['Penny'],
        'Addie Moore': ['Addie'],
        'Addison Rose': ['Addison'],
        'Adel Bye': ['Adella'],
        'Adrianna Gold': ['Adrianne'],
        'Afrodite Night': ['Lauren'],
        'Alana Jade': ['Alana G'],
        'Alana Leigh': ['Alanaleigh'],
        'Aleska Diamond': ['Alexa'],
        'Aletta Ocean': ['Aletta'],
        'Alexia Sky': ['Alexiasky'],
        'Alexis Love': ['Alexis'],
        'Alice Miller': ['Aliana'],
        'Alicia Angel': ['Alicia'],
        'Allie Haze': ['Alliehaze'],
        'Ally Ann': ['Allyann'],
        'Allyssa Hall': ['Allyssa'],
        'Amai Liu': ['Amai'],
        'Ami Emerson': ['Ami'],
        'Amia Miley': ['Abbey'],
        'Amy Brooke': ['Amybrooke'],
        'Amy Reid': ['Amy'],
        'Amy Sativa': ['Amysativa'],
        'Andie Valentino': ['Andie'],
        'Andrea Anderson': ['Aundrea'],
        'Angelina Ashe': ['Angelinaash'],
        'Angelina Brooke': ['Angellina'],
        'Angie Emerald': ['Angela'],
        'Angie Koks': ['Koks'],
        'Anita Pearl': ['Amalie'],
        'Anna Nova': ['Inus'],
        'Anna Stevens': ['Annastevens'],
        'Annabelle Lee': ['Annabelle'],
        'Annette Allen': ['Annette'],
        'Annika Eve': ['Annika'],
        'Anoli Angel': ['Anoli'],
        'April Aubrey': ['April'],
        'April O\'Neil': ['Apriloneil'],
        'Ariadna Moon': ['Ariadna'],
        'Ariel Piper Fawn': ['Gabriella'],
        'Ariel Rebel': ['Ariel'],
        'Ashlee Allure': ['Ashlee'],
        'Ashley Bulgari': ['Bulgari'],
        'Ashley Jane': ['Ashleyjane'],
        'Ashley Jensen': ['Jensen'],
        'Ashley Stillar': ['Nicol'],
        'Ashlyn Rae': ['Ashlynrae'],
        'Asuna Fox': ['Asuna'],
        'Athena Faris': ['Ms Faris'],
        'Athena Palomino': ['Palomino'],
        'Austin Reines': ['Austin'],
        'Ava Skye': ['Sarahjo'],
        'Beata Undine': ['Beata'],
        'Bella Blue': ['Bella B'],
        'Bella Cole': ['Nikala'],
        'Bella Rossi': ['Nadea'],
        'Bernie Svintis': ['Bernie'],
        'Billie Star': ['Pinkule'],
        'Billy Raise': ['Billie'],
        'Black Angelika': ['Angelica'],
        'Black Panther': ['Alexcia'],
        'Bliss Lei': ['Bliss'],
        'Boroka Balls': ['Boroka'],
        'Bree Olson': ['Brea'],
        'Brigitte Hunter': ['Layna'],
        'Brynn Tyler': ['Brynn'],
        'Callie Dee': ['Calliedee'],
        'Capri Anderson': ['Capri'],
        'Carin Kay': ['Karin'],
        'Carli Banks': ['Carli'],
        'Carmen Gemini': ['Gemini'],
        'Carmen Kinsley': ['Carman'],
        'Carmen McCarthy': ['Carmin'],
        'Casey Donell': ['Tonya'],
        'Casey Nohrman': ['Elza A'],
        'Cassandra Calogera': ['Cassandra'],
        'Cate Harrington': ['Cate'],
        'Celeste Star': ['Celeste'],
        'Celina Cross': ['Celina'],
        'Charlie Laine': ['Charlie'],
        'Charlie Lynn': ['Charlielynn'],
        'Charlotte Stokely': ['Charlotte'],
        'Chastity Lynn': ['Chastity'],
        'Chloe Couture': ['Chloe Cherry'],
        'Chloe James': ['Chloejames'],
        'Chloe Morgan': ['Britne'],
        'Christie Lee': ['Christine'],
        'Christine Alexis': ['Chris'],
        'Cindy Dee': ['Nitca'],
        'Cindy Hope': ['Cindy'],
        'Cindy Hope': ['Klaudia'],
        'Cindy Shine': ['Yvonne'],
        'Cira Nerri': ['Katy P'],
        'Connie Carter': ['Conny'],
        'Connie Rose': ['Ninoska'],
        'Courtney Cummz': ['Courtney'],
        'Crissy Moon': ['Crissy'],
        'Crissy Snow': ['Crissysnow'],
        'Cristal Matthews': ['Cristal'],
        'Crystal Maiden': ['Juliya'],
        'Dana Sinnz': ['Dina'],
        'Dani Jensen': ['Dani'],
        'Danielle Maye': ['Danielle'],
        'Danielle Trixie': ['Jess'],
        'Daphne Angel': ['Daphne'],
        'Deena Daniels': ['Deanna'],
        'Deja Move': ['Lussy M'],
        'Demi Scott': ['Sally'],
        'Deny Moor': ['Tea'],
        'Devi Emmerson': ['Devi'],
        'Dido Angel': ['Kira'],
        'Dolly Diore': ['Diore'],
        'Dominic Anna': ['Dominica'],
        'Eden Adams': ['Edenadams'],
        'Eileen Sue': ['Eileen'],
        'Elena Rivera': ['Elena'],
        'Elina Mikki': ['Mikki'],
        'Elizabeth Anne': ['Elizabethanne'],
        'Emy Reyes': ['Emy'],
        'Eufrat Mai': ['Ella'],
        'Eva Gold': ['Eva'],
        'Evah Ellington': ['Ellington'],
        'Eve Angel': ['Eve'],
        'Eveline Dellai': ['Evelin'],
        'Evelyn Baum': ['Evelyn'],
        'Evelyn Cage': ['Linna'],
        'Faina Bona': ['Faina'],
        'Faith Leon': ['Faith'],
        'Faye Reagan': ['Faye'],
        'Faye X Taylor': ['Fayex'],
        'Federica Hill': ['Federica'],
        'Felicia Rain': ['Lolly J'],
        'Ferrera Gomez': ['Ferrera'],
        'Franziska Facella': ['Franziska'],
        'Frida Stark': ['Frida'],
        'Gabriella Lati': ['Esegna'],
        'Georgia Jones': ['Georgia'],
        'Ginger Lee': ['Ginger'],
        'Goldie Baby': ['Giselle'],
        'Goldie Glock': ['Violet'],
        'Haley Sweet': ['Haleysweet'],
        'Hannah West': ['Hanna'],
        'Heather Starlet': ['Katie'],
        'Heidi Harper': ['Heidi C'],
        'Holly Fox': ['Hollyfox'],
        'Ivana Sugar': ['Vania'],
        'Izzy Delphine': ['Delphine'],
        'Jacqueline Sweet': ['Zara'],
        'Jada Gold': ['Caise'],
        'Jaelyn Fox': ['Jaelyn'],
        'Jana Jordan': ['Felicity'],
        'Jana Sheridan': ['Sheridan'],
        'Jasmine Davis': ['Polly'],
        'Jasmine Rouge': ['Jasmine'],
        'Jassie James': ['Jassie'],
        'Jayme Langford': ['Alana'],
        'Jenna Presley': ['Jenna'],
        'Jenni Carmichael': ['Lindsay'],
        'Jenni Czech': ['Jenni'],
        'Jenni Lee': ['Jenny'],
        'Jenny Appach': ['Jenniah'],
        'Jenny Sanders': ['Andrea'],
        'Jeny Baby': ['Jeny'],
        'Jessi Gold': ['Marsa'],
        'Jessica Foxx': ['Serendipity'],
        'Jessica Valentino': ['Dessa'],
        'Jessie Cox': ['Jessie'],
        'Jessika Lux': ['Miesha'],
        'Jewel Affair': ['Jamie'],
        'Joanna Pret': ['Marfa'],
        'Jordan Bliss': ['Jordanbliss'],
        'Judith Fox': ['Judith'],
        'Juicy Pearl': ['Pearl'],
        'Juliana Grandi': ['Julie'],
        'Kacey Jordan': ['Kacey'],
        'Kali Lane': ['Kalilane'],
        'Kandi Milan': ['Kandi'],
        'Kara Novak': ['Karanovak'],
        'Kari Sweet': ['Kari S'],
        'Karina Laboom': ['Karina'],
        'Karlie Montana': ['Janelle'],
        'Kathleen Kruz': ['Kate'],
        'Katie Jordin': ['Katiejordin'],
        'Katie Kay': ['Katiek'],
        'Katya Clover': ['Clover'],
        'Kayla Louise': ['Kaula'],
        'Kaylee Heart': ['Kaylee'],
        'Keira Albina': ['Adelle'],
        'Kelly Summer': ['Lindie'],
        'Kennedy Kressler': ['Kennedy'],
        'Kimber Lace': ['Kimber'],
        'Kimberly Allure': ['Kimberly'],
        'Kimberly Cox': ['Fawn'],
        'Kimmie Cream': ['Kimmie'],
        'Kira Lanai': ['Kiralanai'],
        'Kira Zen': ['Kirra'],
        'Kirsten Andrews': ['Traci'],
        'Kody Kay': ['Kody'],
        'Kristina Manson': ['Krystyna'],
        'Kristina Rose': ['Kristinarose'],
        'Kristina Rud': ['Sharon'],
        'Kristina Wood': ['Kristina'],
        'Krisztina Banks': ['Christina'],
        'Kyra Black': ['Toni'],
        'Kyra Steele': ['Kyra'],
        'Lady Dee': ['Lady D'],
        'Lana Violet': ['Lanaviolet'],
        'Laura Crystal': ['Lauracrystal'],
        'Lea Tyron': ['Lea'],
        'Leah Luv': ['Leah'],
        'Leighlani Red': ['Leigh'],
        'Leila Smith': ['Leila'],
        'Lena Nicole': ['Kaela'],
        'Leony April': ['Jesica'],
        'Lexi Belle': ['Lexie'],
        'Lexi Diamond': ['Lexidiamond'],
        'Leyla Black': ['Jenet'],
        'Lia Chalizo': ['Dimitra'],
        'Lilian Lee': ['Lilian'],
        'Liliane Tiger': ['Liliane'],
        'Lily Cute': ['Lily'],
        'Lily Lake': ['Violetta'],
        'Lindsay Kay': ['Grace'],
        'Lindsey Olsen': ['Talya'],
        'Liona Levi': ['Krissie'],
        'Lisa Musa': ['Roberta'],
        'Lita Phoenix': ['Sveta'],
        'Little Caprice': ['Lolashut'],
        'Little Rita': ['Natalya'],
        'Liz Honey': ['Britney'],
        'Lola Chic': ['Lilit'],
        'Lolly Gartner': ['Lolly'],
        'Lora Craft': ['Lora'],
        'Loreen Roxx': ['Loreen'],
        'Lorena Garcia': ['Lorena'],
        'Louisa Lanewood': ['Lanewood'],
        'Lucie Theodorova': ['Alena'],
        'Lucy Ive': ['Lucy'],
        'Lucy Lux': ['Lucylux'],
        'Lynn Love': ['Lynnlove'],
        'Lynn Pleasant': ['Lynn'],
        'Mackenzee Pierce': ['Kenzie'],
        'Madison Parker': ['Maddy'],
        'Maggie Gold': ['Maggies'],
        'Mai Ly': ['Mai'],
        'Mandy Dee': ['Stacy'],
        'Maria Devine': ['Quenna'],
        'Marina Mae': ['Marina'],
        'Marissa Mendoza': ['Marissa'],
        'Marlie Moore': ['Marlie'],
        'Mary Kalisy': ['Kalisy'],
        'Maya Hills': ['Maya'],
        'Mckenzee Miles': ['Mckenzee'],
        'Meggan Mallone': ['Meggan'],
        'Melanie Taylor': ['Melanie'],
        'Melena Maria Rya': ['Marta'],
        'Melissa Matthews': ['Melissa'],
        'Mellisa Medisson': ['Barbra'],
        'Melody Kush': ['Melody'],
        'Merry Pie': ['Patritcy'],
        'Mia Hilton': ['Miahilton'],
        'Mia Me': ['Lola'],
        'Mia Moon': ['Mia'],
        'Micah Moore': ['Micah'],
        'Michelle Brown': ['Michele'],
        'Michelle Maylene': ['Michelle'],
        'Michelle Moist': ['Michellemoist'],
        'Michelle Myers': ['Michellemyers'],
        'Miley Ann': ['Mileyann'],
        'Mili Jay': ['Mili'],
        'Milla Yul': ['Minnie'],
        'Missy Nicole': ['Missy'],
        'Molly Madison': ['Mollymadison'],
        'Monica Beluchi': ['Natosha'],
        'Monica Sweat': ['Marsha'],
        'Monica Sweet': ['Dana'],
        'Monika Cajth': ['Monique'],
        'Monika Thu': ['Sassy'],
        'Monika Vesela': ['Monika'],
        'Monna Dark': ['Monna'],
        'Nadia Taylor': ['Angelina'],
        'Nadine Greenlaw': ['Zenia'],
        'Nancy Ace': ['Nancy A'],
        'Nancy Bell': ['Nancy'],
        'Naomi Cruise': ['Tyra'],
        'Natali Blond': ['Natali'],
        'Natalia Forrest': ['Nataliex'],
        'Nataly Gold': ['Morgan'],
        'Nathaly Cherie': ['Oprah'],
        'Nelli Sulivan': ['Nelly'],
        'Nessa Shine': ['Agnessa'],
        'Neyla Small': ['Jorden'],
        'Nici Dee': ['Nici'],
        'Nicole Ray': ['Nicoleray'],
        'Nika Noire': ['Niki'],
        'Nikita Black': ['Alyssia'],
        'Nikki Chase': ['Simone'],
        'Nikki Vee': ['Nikkivee'],
        'Nikko Jordan': ['Eriko'],
        'Niky Sweet': ['Nikysweet'],
        'Nina Stevens': ['Sierra'],
        'Olivia Brown': ['Nyusha'],
        'Olivia La Roche': ['Olivia'],
        'Oxana Chic': ['Oxana'],
        'Paige Starr': ['Kellie'],
        'Paris Diamond': ['Diamond'],
        'Paris Parker': ['Paris'],
        'Paulina James': ['Paulina'],
        'Pavlina St.': ['Paula'],
        'Pearl Ami': ['Edyphia'],
        'Persia DeCarlo': ['Persia'],
        'Petra E': ['Carmen'],
        'Playful Ann': ['Anne'],
        'Presley Maddox': ['Presley'],
        'Rebecca Blue': ['Rebeccablue'],
        'Reena Sky': ['Reena'],
        'Regina Prensley': ['Evonna'],
        'Renee Perez': ['Renee'],
        'Rose Delight': ['Rosea'],
        'Roxanna Milana': ['Taylor'],
        'Roxy Carter': ['Amber'],
        'Roxy Panther': ['Roxy'],
        'Ruby Flame': ['Ruby'],
        'Sabina Blue': ['Viva'],
        'Samantha Sin': ['Heather'],
        'Samantha Wow': ['Lucie'],
        'Sammie Rhodes': ['Sammie'],
        'Sandra Bina': ['Adri'],
        'Sandra Kalermen': ['Carrie'],
        'Sandra Shine': ['Sandra'],
        'Sandy Joy': ['Sandy'],
        'Sandy Summers': ['Sandysummers'],
        'Sarah Blake': ['Sarah'],
        'Sarai Keef': ['Sarai'],
        'Sasha Cane': ['Sasha'],
        'Sasha Rose': ['Yanka'],
        'Scarlett Fay': ['Scarlettfay'],
        'Scarlett Nika': ['Nikka'],
        'Sera Passion': ['Sera'],
        'Shrima Malati': ['Sima'],
        'Shyla Jennings': ['Shyla'],
        'Silvie Deluxe': ['Sylvia'],
        'Smokie Flame': ['Smokie'],
        'Sonya Durganova': ['Tessa'],
        'Stasia': ['Aniya'],
        'Stephanie Sage': ['Sage'],
        'Sugar Baby': ['Bridget'],
        'Summer Breeze': ['Ianisha'],
        'Summer Silver': ['Summersilver'],
        'Summer Solstice': ['Solstice'],
        'Suzie Diamond': ['Suzie'],
        'Suzy Black': ['Suze'],
        'Talia Shepard': ['Victoria'],
        'Tanner Mayes': ['Tannermays'],
        'Tarra White': ['Martha'],
        'Teena Dolly': ['Pavla'],
        'Tegan Jane': ['Tegan'],
        'Tereza Ilova': ['Tereza'],
        'Teri Sweet': ['Teresina'],
        'Tess Lyndon': ['Tess'],
        'Tiffany Diamond': ['Vendula'],
        'Tiffany Sweet': ['Tiff'],
        'Timea Bella': ['Luciana'],
        'Traci Lynn': ['Hallee'],
        'Tracy Gold': ['Noleta'],
        'Tyra Moon': ['Athina'],
        'Valerie Herrera': ['Valerie'],
        'Vanessa Monroe': ['Vanessa'],
        'Veronica Hill': ['Veronicahill'],
        'Veronica Jones': ['Veronica'],
        'Veronique Vega': ['Veronique'],
        'Victoria Puppy': ['Victoria P'],
        'Victoria Sweet': ['Victoriasweet'],
        'Vika Lita': ['Viera'],
        'Violette Pink': ['Violette'],
        'Whitney Conroy': ['Whitney'],
        'Yasmine Gold': ['Rachel'],
        'Yulia Bright': ['Angie'],
        'Zazie Sky': ['Zazie'],
        'Zeina Heart': ['Zeina'],
        'Zena Little': ['Xenia'],
        'Zuzana Z': ['Jujana'],
    },
    16: {
        'Bailey Brooke': ['Bailey Brookes'],
    },
    17: {
        'Scarlet Domingo': ['Scarlett D'],
    },
    18: {
        'Ada Sanchez': ['Ada S'],
        'Adelle Booty': ['Parvin'],
        'Alektra Sky': ['Darla'],
        'Alice Marshall': ['Dunya'],
        'Alice Smack': ['Mackenzie'],
        'Alison Faye': ['Kendall'],
        'Ananta Shakti': ['Lusil'],
        'Anita Sparkle': ['Rebecca'],
        'Anna Taylor': ['Madelyn'],
        'Ariadna Moon': ['Ariadna'],
        'Arian Joy': ['Dinara'],
        'Ariel Rose': ['Ariel R'],
        'Arika Foxx': ['Arika'],
        'Aruna Aghora': ['Zarina'],
        'Arya Fae, Megan Sage, Nina North': ['Yoga'],
        'Aubree Jade': ['Mariah'],
        'Autumn Viviana': ['Viviana'],
        'Ava Dalush': ['Ava'],
        'Bella Rossi': ['Bella'],
        'Bonnie Shai': ['Viki'],
        'Callie Nicole': ['Callie'],
        'Camila': ['Betty'],
        'Camila': ['Jane'],
        'Candy C': ['Carre'],
        'Carol Miller': ['Serena'],
        'Casi James': ['Casi J'],
        'Chloe Blue': ['Ema'],
        'Chloe Couture': ['Chloe Cherry'],
        'Diana Dali': ['Avery'],
        'Dominica Phoenix': ['Petra'],
        'Emma Brown': ['Ariana'],
        'Erika Bellucci': ['Gerta'],
        'Grace C': ['Sophia'],
        'Inga E': ['Colette'],
        'Izi': ['Gabi'],
        'Janna': ['Jana'],
        'Jay Dee': ['Lada'],
        'Jessi Gold': ['Catania'],
        'Joanna Pret': ['Joanna'],
        'Kajira Bound': ['Kajira'],
        'Karina Grand': ['Madison'],
        'Kate G.': ['Rosanna'],
        'Katie Cummings': ['Katie C'],
        'Katie Kay': ['Katie K'],
        'Kortny': ['Kail'],
        'Krista Evans': ['Krista'],
        'Kristall Rush': ['Erica'],
        'Kristall Rush': ['Sasha'],
        'Lena Love': ['Bailey'],
        'Lilu Tattoo': ['Vilia'],
        'Lily Labeau': ['Lily L'],
        'Liona Levi': ['Zoi'],
        'Lisa C': ['Janette'],
        'Lisa Smiles': ['Argentina'],
        'Lola Taylor': ['Tori'],
        'Mai Ly': ['Mai'],
        'Margarita C': ['Peachy'],
        'Marina Visconti': ['Sheila'],
        'Mariya C': ['Fantina'],
        'Mariya C': ['Olga'],
        'Marly Romero': ['Mara'],
        'Mia Reese': ['Eva'],
        'Mila Beth': ['Mina'],
        'Milana Blanc': ['Briana'],
        'Milana Blanc': ['Brianna'],
        'Milana Fox': ['Hannah'],
        'Milla Yul': ['Yanie'],
        'Miranda Deen': ['Veiki'],
        'Nadia Bella': ['Nadya'],
        'Nadia Bella': ['Seren'],
        'Netta': ['Jade'],
        'Nicoline': ['Anfisa'],
        'Pola Sunshine': ['Kimberly'],
        'Rahyndee James': ['Rahyndee'],
        'Rebeca Taylor': ['Jordan'],
        'Riley Jensen': ['Riley J'],
        'Rima': ['Aliya'],
        'Rita Rush': ['Luna'],
        'Sabrina Moor': ['Nika'],
        'Sadine Godiva': ['Sadine G'],
        'Sandra Luberc': ['Kameya'],
        'Sarai Keef': ['Sarai'],
        'Selena Stuart': ['Katherine'],
        'Sheri Vi': ['Nora R'],
        'Sierra Sanders': ['Sierra'],
        'Skye West': ['Skye'],
        'Soliel Marks': ['Soleil'],
        'Stella Banxxx': ['Stella'],
        'Sunny Rise': ['Avina'],
        'Taissia Shanti': ['Magda'],
        'Valentina Cross': ['Artemida'],
    },
    19: {
        'Lena Anderson': ['Blaire Ivory'],
    },
    20: {
        'Aaliyah Love': ['Aliyah'],
        'Abigaile Johnson': ['Abby'],
        'Adel Morel': ['Adel M'],
        'Adele Sunshine': ['Sunshine'],
        'Adria Rae': ['Adria'],
        'Adriana Chechik': ['Adriana'],
        'Aidra Fox': ['Aidra'],
        'Aika May': ['Aika'],
        'AJ Applegate': ['Danielle'],
        'Alecia Fox': ['Alecia'],
        'Aleksa Slusarchi': ['Jessica'],
        'Alessandra Jane': ['Aj'],
        'Alexa Grace': ['Alexa'],
        'Alexa Tomas': ['Alina'],
        'Alexis Adams': ['Alexes'],
        'Alexis Crystal': ['Carrie'],
        'Alexis Love': ['Alexis'],
        'Alicia A': ['Jenny'],
        'Allie Haze': ['Allie'],
        'Allison': ['Kristi'],
        'Alyssa Branch': ['Sam'],
        'Alyssia Kent': ['Alyssia'],
        'Amarna Miller': ['Serena'],
        'Ana Foxxx': ['Ana'],
        'Anastasia Morna': ['Anna M'],
        'Anetta V.': ['Veronika'],
        'Angel Piaff': ['Adel'],
        'Angelic Anya': ['Patsy'],
        'Angelica Kitten': ['Angie'],
        'Anita Bellini Berlusconi': ['Anita'],
        'Anna Rose': ['Maria'],
        'Annika Albrite': ['Anikka'],
        'Antonia Sainz': ['Katerina'],
        'Anya Olsen': ['Anya'],
        'Ariana Marie': ['Arianna'],
        'Ariel Piper Fawn': ['Ariel'],
        'Ariel': ['Lillianne'],
        'Artemis': ['Reina'],
        'Ashlyn Molloy': ['Ashley S'],
        'Aubrey Star': ['Aubrey'],
        'Avril Hall': ['Avril'],
        'Bailey Ryder': ['Bailey'],
        'Barbamiska': ['Stevie'],
        'Beata Undine': ['Beatrice'],
        'Belle Knox': ['Belle'],
        'Bethany': ['Crystal'],
        'Blanche Bradburry': ['Barbie'],
        'Blue Angel': ['Leila'],
        'Brea Bennett': ['Breanne'],
        'Bree Daniels': ['Bree'],
        'Bridgit A': ['Becky'],
        'Brooklyn Lee': ['Brooklyn'],
        'Brynn Tyler': ['Brynn'],
        'Candice Luca': ['Kaylee'],
        'Capri Anderson': ['Capri'],
        'Carla Cox': ['Carla'],
        'Cassandra Nix': ['Emily'],
        'Cassidey Rae': ['Cassidy'],
        'Cassie Laine': ['Cassie'],
        'Catie Parker': ['Catie'],
        'Catina': ['Sasha D'],
        'Cayla Lyons': ['Cayla'],
        'Cayla Lyons': ['Hannah'],
        'Celine': ['Kaye'],
        'Charity Crawford': ['Charity'],
        'Charlie Red': ['Charlie'],
        'Charlotte Stokely': ['Charlotte'],
        'Cherry Kiss': ['Leony'],
        'Chloe Amour': ['Amelie'],
        'Chloe Foster': ['Bunny'],
        'Chloe Lynn': ['Chloelynn'],
        'Christine Paradise': ['Christine'],
        'Connie Carter': ['Connie'],
        'Dakoda Brookes': ['Riley'],
        'Daphne Klyde': ['Daphne'],
        'Davina Davis': ['Addison C'],
        'Deina': ['Stacy'],
        'Diana Fox': ['Diana'],
        'Diana G': ['Mira'],
        'Dido Angel': ['Susie'],
        'Dillion Harper': ['Dillion'],
        'Dominic Anna': ['Dominica'],
        'Dominika C.': ['Dominique'],
        'Eileen Sue': ['Stefanie'],
        'Elisa': ['Liv'],
        'Elle Alexandra': ['Elle'],
        'Ellena Woods': ['Jocelyn'],
        'Elouisa': ['Natali'],
        'Emily Brix': ['Emily B'],
        'Emily Grey': ['Emilie'],
        'Emma Mae': ['Emma'],
        'Erica Fontes': ['Erica'],
        'Eufrat Mai': ['Eufrat'],
        'Eveline Dellai': ['Eveline'],
        'Faye Reagan': ['Faye'],
        'Ferrera Gomez': ['Katka'],
        'Foxxi Black': ['Foxi'],
        'Foxy Di': ['Kate'],
        'Franziska Facella': ['Francesca'],
        'Georgia Jones': ['Georgia'],
        'Gigi Allens': ['GiiGi'],
        'Gigi Labonne': ['Gigi'],
        'Gigi Rivera': ['Gigi R'],
        'Gina Devine': ['Jasmine'],
        'Gina Gerson': ['Gina'],
        'Gina': ['Nicole'],
        'Gwen': ['Anna'],
        'Hannah Hawthorne': ['Hanna'],
        'Hannah Hays': ['Rainbow'],
        'Hayden Hawkens': ['Hayden H'],
        'Hayden Winters': ['Hayden'],
        'Heather Carolin': ['Scarlett'],
        'Heather Night': ['Tina'],
        'Heather Starlet': ['Ruby'],
        'Heidi Romanova': ['Heidi R'],
        'Henessy': ['Alina H'],
        'Irina J': ['Michelle'],
        'Irina K': ['Stasha'],
        'Isabel B': ['Oliya'],
        'Ivana Sugar': ['Eve A'],
        'Iwia': ['Ivy'],
        'Izabelle A': ['Sandy'],
        'Izzy Delphine': ['Izzy'],
        'Jade Baker': ['Jade'],
        'Jana Mrhacova': ['Willow'],
        'Janetta': ['Eve'],
        'Janny Manson': ['Jenny M'],
        'Jaslene Jade': ['Natalie'],
        'Jayden Taylors': ['Jayden'],
        'Jenna Ross': ['Jenna'],
        'Jenni Czech': ['Jenni'],
        'Jericha Jem': ['Jericha'],
        'Jessica Rox': ['Kristen'],
        'Jessie Andrews': ['Jessie'],
        'Jessie Rogers': ['Carmen'],
        'Jillian Janson': ['Jillian'],
        'Joleyn Burst': ['Katia'],
        'Joseline Kelly': ['Joseline'],
        'Julia I': ['Jewel'],
        'Kalea Taylor': ['Laura'],
        'Kamila': ['Heather'],
        'Kari Sweet': ['Katherine'],
        'Karina White': ['Karina'],
        'Karina': ['Baby'],
        'Kasey Chase': ['Carlie'],
        'Kassondra Raine': ['Kassondra'],
        'Katerina': ['Mikah'],
        'Katie Oliver': ['Gabriella'],
        'Katy Jayne': ['Katie Jayne'],
        'Katy Rose': ['Kim'],
        'Katya Clover': ['Clover'],
        'Keira Albina': ['Keira'],
        'Kelly E': ['Natasha B'],
        'Kendall White': ['Kendall'],
        'Kenna James': ['Kenna'],
        'Kennedy Kressler': ['Kennedy'],
        'Kenze Thomas': ['Kenzie'],
        'Kiara Lord': ['Alena'],
        'Kiera Winters': ['Kiera'],
        'Kimberly Kato': ['Kato'],
        'Kimmy Granger': ['Kimmy'],
        'Kinsley Ann': ['Kinsley'],
        'Kira Thorn': ['Kira'],
        'Kira Zen': ['Kirra'],
        'Kirsten Nicole Lee': ['Kirsten Lee'],
        'Kitty Jane': ['Kitty'],
        'Kristen Scott': ['Kristin Scott'],
        'Krystal Boyd': ['Angelica'],
        'Kya': ['Katy'],
        'Kylie Nicole': ['Kylie'],
        'Lady Dee': ['Dina'],
        'Lauren Crist': ['Lisa'],
        'Leila Smith': ['Janie'],
        'Lena Anderson': ['Lena'],
        'Lena Love': ['Pam'],
        'Lena': ['Tasha'],
        'Leo': ['Tatiana'],
        'Leonie': ['Holly'],
        'Lexi Belle': ['Lexi'],
        'Lexi Dona': ['Carrol'],
        'Lexi Foxy': ['Nella'],
        'Lexi Layo': ['Lexy'],
        'Lexie Fox': ['Lolita'],
        'Lia Lor': ['Lia'],
        'Lilit Sweet': ['Lilit'],
        'Lilith Lee': ['Sweetie'],
        'Lilu Moon': ['Lilu'],
        'Lily Ivy ': ['Lilly Ivy'],
        'Lily Labeau': ['Lilly'],
        'Lindsey Olsen': ['Nastia'],
        'Lisa Dawn': ['Liza Dawn'],
        'Little Caprice': ['Caprice'],
        'Livia Godiva': ['Olivia'],
        'Lorena Garcia': ['Lorena'],
        'Lovita Fate': ['Lovita'],
        'Lucy Li': ['Teal'],
        'Lynette': ['Maya'],
        'Lyra Louvel': ['Lyra'],
        'Mae Olsen': ['Anais'],
        'Malena Morgan': ['Malena'],
        'Marica Hase': ['Marica'],
        'Marie McCray': ['Marie M.'],
        'Marry Queen': ['Mary'],
        'Maryjane Johnson': ['Maryjane'],
        'Masha D.': ['Jackie'],
        'Megan Promesita': ['Ivana'],
        'Melanie Rios': ['Melanie'],
        'Melena Maria Rya': ['Malena A'],
        'Mia Hilton': ['Lana'],
        'Mia Lina': ['Mia'],
        'Mia Malkova': ['Mia M'],
        'Mia Manarote': ['Addison'],
        'Michaela Isizzu': ['Mila K'],
        'Mila Azul': ['Milla'],
        'Monika Benz': ['Anastasia'],
        'Monika Benz': ['Monika'],
        'Monika Thu': ['Monique'],
        'Nadia Nickels': ['Nadia'],
        'Nadine': ['Tess'],
        'Nancy Ace': ['Nancy'],
        'Naomi Bennet': ['Naomi B'],
        'Naomi Nevena': ['Lily'],
        'Natali Blond': ['Megan'],
        'Nataly Gold': ['Linsay'],
        'Nedda A': ['Miss Pac Man'],
        'Nelly A': ['Chantal'],
        'Nessa Devil': ['Katrina'],
        'Nici Dee': ['Nikki'],
        'Nika': ['Nicola'],
        'Nikki Fox': ['Niki'],
        'Nikki Peach': ['Nikki Peaches'],
        'Nikki Stills': ['Nastya'],
        'Nina James': ['Nina'],
        'Olivia Grace': ['Bambi'],
        'Paige Owens': ['Paige'],
        'Paloma B': ['Reese'],
        'Paula Shy': ['Misty'],
        'Penelope Lynn': ['Lola'],
        'Pinky June': ['Anneli'],
        'Presley Hart': ['Presley'],
        'Rebecca Volpetti': ['Rebecca'],
        'Red Fox': ['The Red Fox'],
        'Ria Sunn': ['Ria Sun'],
        'Rima B': ['Ellie'],
        'Rosemary Radeva': ['Angel'],
        'Sabrisse': ['Miu'],
        'Samantha Heat': ['Annemarie'],
        'Samantha Jolie': ['Samantha'],
        'Samantha Rone': ['Sammy'],
        'Sapphira A': ['Maya M'],
        'Sarka': ['Tabitha'],
        'Sasha Grey': ['Sasha'],
        'Satin Bloom': ['Marie'],
        'Scyley Jam': ['Viktoria'],
        'Shrima Malati': ['Shrima'],
        'Sicilia': ['Cecilia'],
        'Silvie Deluxe': ['Silvie'],
        'Silvie Luca': ['Naomi'],
        'Sindy Vega': ['Cindy'],
        'Sinovia': ['Tracy'],
        'Sophia Fiore': ['Sophia'],
        'Sophia Knight': ['Sophie'],
        'Stacy Cruz': ['Cornelia'],
        'Stefanie': ['Stephanie'],
        'Summer Breeze': ['Corinne'],
        'Sunny A': ['Aria'],
        'Susan Ayn': ['Paulina'],
        'Suzie Carina': ['Suzie C'],
        'Sybil A': ['Sybil'],
        'Talia Mint': ['Talia'],
        'Talia Shepard': ['Kat'],
        'Taylor Sands': ['Heidi'],
        'Teena Dolly': ['Grace'],
        'Tiffany Fox': ['Tiffany F'],
        'Tiffany Thompson': ['Tiffany'],
        'Tori Black': ['Tori'],
        'Tracy Lindsay': ['Summer'],
        'Tracy Smile': ['Julie'],
        'Vanessa': ['Casey'],
        'Vanna Bardot': ['Vanna'],
        'Veronica Clark': ['Veronica'],
        'Veronica Radke': ['Scarlet'],
        'Vicki Chase': ['Vicky'],
        'Vicky Love': ['Vicki'],
        'Victoria Blaze': ['Gianna'],
        'Victoria Lynn': ['Chelsea'],
        'Victoria Puppy': ['Bea'],
        'Victoria Puppy': ['Poppy'],
        'Victoria Rae Black': ['Victoria'],
        'Victoria Sweet': ['Chloe'],
        'Vika T': ['Leah'],
        'Vinna Reed': ['Vinna'],
        'Violette Pink': ['Pink Violet'],
        'Xandra B': ['Tara'],
        'Zazie Sky': ['Zazie'],
        'Zena Little': ['Sandra'],
        'Zoe': ['Klara'],
        'Zoey Kush': ['Star'],
    },
    21: {
        'Alena H': ['Helen'],
        'Goldie Baby': ['Ms White-Kitten'],
        'Mishelle Klein': ['Molly'],
    },
    22: {
        'Morgan Layne': ['Morgan'],
    },
    23: {
        'Katya Clover': ['Clover'],
        'Nataly Von': ['Natasha Von'],
        'Goldie Baby': ['Nikia'],
        'Olivia Jameson': ['Olivka'],

    },
    24: {
        'Apolonia Lapiedra': ['Apolonia'],
        'Bambi Dee': ['Td Bambi'],
        'Lola Taylor': ['Lolita Taylor'],
        'Scarlet Domingo': ['Scarlet'],
    },
    25: {
        'Susan Ayn': ['Susan Ayne'],
    },
    26: {
        'Luna Corazon': ['Luna Corazón'],
    },
    27: {
        'London Keyes': ['London Keys'],
    },
    28: {
        'Gabriella Lati': ['Gabrielle Lati'],
    },
    29: {
        'Krystal Boyd': ['Abbie'],
    },
    30: {
        'Stefanie Moon': ['Stefany'],
    },
    31: {
        'Alais Peach': ['Alais'],
        'Arabella Langford': ['Arabella'],
        'Bad Dolly': ['Dolly'],
        'Cory Spice': ['Cory'],
        'Darina Nikitina': ['Darina'],
        'Domenica': ['Sam'],
        'Emma Green': ['Daisy'],
        'Fayth On Fire': ['Fayth'],
        'Izzy Delphine': ['Izzy'],
        'Kaitlin Grey': ['Buttercup'],
        'Katarina Hartlova': ['Katarina'],
        'Katie Thornton': ['Katie'],
        'Lisa Scott': ['Lisa'],
        'Liz Rainbow': ['Liz'],
        'Olga Cabaeva': ['Olga'],
        'Roxy Mendez': ['Roxy'],
        'Samantha Bentley': ['Samantha'],
    },
    32: {
        'QueenSnake': ['Qs'],
    },
    33: {
        'Penelope Cum': ['Penelope'],
    },
    34: {
        'Ariadna Moon': ['Ariadna'],
    },
    35: {
        'Victoria Puppy': ['Victoria P'],
    },
    36: {
        'Casey Norhman': ['Casey'],
        'Cayla Lyons': ['Cayla'],
        'Lady Dee': ['Lady D'],
    },
    37: {
        'Athina Love': ['Athina'],
    },
    38: {
        'Niki Sweet': ['Nikki Sweet'],
    },
    39: {
        'Angie Moon': ['Arianna'],
        'Kristall Rush': ['Anna G'],
        'Lisa Luv': ['Lisa C'],
        'Silvia Jons': ['Gabi'],
    },
    40: {
        'Natalia Andreeva': ['Natalia A'],
    },
}

ActorsStudioIndexes = {
    0: ['21Sextury', '21 Sextury', 'Footsie Babes'],
    1: ['Babes'],
    2: ['Bang Bros'],
    3: ['ClubSeventeen'],
    4: ['CumLouder'],
    5: ['Deeper', 'Tushyraw', 'Tushy', 'Blacked', 'Blackedraw', 'Vixen'],
    6: ['Evilangel'],
    7: ['FuelVirtual'],
    8: ['Holed'],
    9: ['LegalPorno'],
    10: ['Joymii'],
    11: ['Jules Jordan'],
    12: ['Kink'],
    13: ['ManyVids'],
    14: ['Mylf'],
    15: ['Nubiles'],
    16: ['Porn Pros'],
    17: ['Porndoe Premium'],
    18: ['TeamSkeet'],
    19: ['Twistys'],
    20: ['X-Art'],
    21: ['DDFProd'],
    22: ['Reality Kings'],
    23: ['WowGirls'],
    24: ['Private'],
    25: ['VIPissy'],
    26: ['Erika Lust Films'],
    27: ['Bang Com'],
    28: ['Milehigh', 'Doghouse Digital'],
    29: ['Rocco Siffredi'],
    30: ['Puffy Network'],
    31: ['HuCows.com'],
    32: ['QueenSnake', 'QueenSect'],
    33: ['VirtualTaboo'],
    34: ['VirtualRealPorn'],
    35: ['VR Bangers'],
    36: ['HighTechVR'],
    37: ['BadoinkVR'],
    38: ['CzechVR'],
    39: ['Teen Mega World'],
    40: ['Hegre'],
}
